name: Run tests on pull request and auto merge dependabot pull requests

on: 
  workflow_call:
    secrets: 
      DEPENDABOT_GITHUB_PAT:
        required: true
jobs:
  dependabot_automerge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test --if-present
