name: Run tests on pull request and auto merge dependabot pull requests

on: 
  workflow_call:
    secrets: 
      DEPENDABOT_GITHUB_PAT:
        required: true
        
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "12"
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Run tests
      run: npm run test --if-present
      shell: bash
