name: Run tests on pull request and auto merge dependabot pull requests

on: workflow_call
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: "12"
      
      - name: Install dependencies
        run: npm ci

      - name: Get IS_NPM
        run: echo "IS_NPM=$(if [ -f package.json ]; then echo 1; else echo 0; fi)" >> $GITHUB_ENV
      
      - name: Get IS_MAVEN
        run: echo "IS_MAVEN=$(if [ -f pom.xml ]; then echo 1; else echo 0; fi)" >> $GITHUB_ENV

      - name: Get IS_GRADLE
        run: echo "IS_GRADLE=$(if [ -f build.gradle ]; then echo 1; else echo 0; fi)" >> $GITHUB_ENV
      
      - name: Run tests for NPM
        if: env.IS_NPM == 1
        run: npm test --if-present
        
      - name: Run tests for Java (Maven)
        if: ${{ always() && env.IS_MAVEN == 1 }}
        run: mvn test
        
      - name: Run tests for Java (Gradle)
        if: ${{ always() && env.IS_GRADLE == 1 }}
        run: ./gradlew test
        
      - name: Run tests for Python
        if: ${{ always() }}
        run: python -m unittest
        
      - name: Get github token
        if: ${{ success() && github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v1
        id: dependabot-metadata
        with:
          alert-lookup: true
          github-token: "${{ secrets.DEPENDABOT_GITHUB_PAT }}"

      - name: Merge dependabot PR
        if: ${{ success() && github.actor == 'dependabot[bot]'}}
        uses: nick-fields/retry@v2.8.2
        with:
          command: gh pr merge --auto --merge "$PR_URL"
          max_attempts: 10
          timeout_seconds: 60
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Notify slack on success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() && github.actor == 'dependabot[bot]' }}
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: "Repository ${{github.event.repository.name}} was updated successfully as tests succeeded."
          SLACK_FOOTER: "Affected dependencies: ${{steps.dependabot-metadata.outputs.dependency-names}}"
          SLACK_USERNAME: "Dependabot"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/27347476?s=200&v=4"
          MSG_MINIMAL: commit
      
      - name: Notify slack on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: "${{ steps.dependabot-metadata.outputs.cvss >= 9 && '@channel' || ''}} Repository ${{github.event.repository.name}} was not updated due to failing tests."
          SLACK_FOOTER: "Affected dependencies: ${{steps.dependabot-metadata.outputs.dependency-names}}"
          SLACK_COLOR: "#FF0000"
          SLACK_USERNAME: "Dependabot"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/27347476?s=200&v=4"
          MSG_MINIMAL: commit
